name: Publish to PyPI

# on:
#   release:
#     types: [published]
on: [push]

jobs:
  publish:
    name: Publish Package to PyPI
    runs-on: ubuntu-latest
    env:
      ARCHIVE_NAME: ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}
      SDK_NAME: ''
    steps:
      - name: Echo ARCHIVE_NAME 
        run: echo "$ARCHIVE_NAME"
      - name: Echo env
        run: echo "${{ env.ARCHIVE_NAME }}"
      - name: Echo tag_name
        run: |
          sdk_name="v0.0.1"
          if [[ "$sdk_name" == v* ]]; then
            sdk_name="${sdk_name#v}"
          fi
          echo "SDK Name: $sdk_name"
          echo "::set-output name=SDK_NAME::$sdk_name"
      - name: Echo sdk_name
        run: echo "${{ env.SDK_NAME }}"
      
      # - name: Install twine
      #   run: python -m pip install --upgrade pip setuptools wheel twine

      # - name: Download source
      #   run: wget ${{ github.event.release.tarball_url }}
        
      # - run: ls -R # 检查工作目录下的文件结构
      # - name: Build and publish
      #   env:
      #     TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
      #     TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      #   run: |
      #     twine upload --repository-url https://upload.pypi.org/legacy/ ./*